### ISSUE TITLE
Possible formatting issue in published files

### ISSUE THREAD

**Issue by claremacrae** [s-blu/obsidian_dataview_example_vault#28]
Hello, first of all thank you for this incredible treasure trove of dataview information!

I tried using the published version of it, and I wonder whether there is some text that is not being rendered?

URL:
https://s-blu.github.io/obsidian_dataview_example_vault/20%20Dataview%20Queries/Basic%20List%20Queries/

![image](https://user-images.githubusercontent.com/4840096/189346638-9504f4b3-4f08-4330-8c7a-162b1807e204.png)

**Comment by s-blu** [comment]
Oh dear. Yes, certainly, I think I have an idea what happened here. Thanks alot for the pointer! I'll work on a fix ASAP. As a workaround: to see the raw data, you can click on the edit button at the upper right corner of pages to view the file unaltered in github. There, everything should be available as expected.

**Comment by claremacrae** [comment]
Nice workaround idea - thank you!

**Comment by s-blu** [comment]
My mechanism to extract the tags from the body to the frontmatter in order to make them usable for navigation was a tad too greedy and just ate _all_ tags in the file 😆 I now restrict the replacement to the area before the first heading, so this issue should be resolved.

Thanks again for reporting!

**Comment by claremacrae** [comment]
Thank you for fixing, and so soon!
