### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by AveryVeilfaire** [s-blu/obsidian_dataview_example_vault#46]
The example repository seems to be missing quite a bit of content compared to the online published version.

**Comment by claremacrae** [comment]
Can you give an example?

**Comment by AveryVeilfaire** [comment]
https://s-blu.github.io/obsidian_dataview_example_vault/tagindex/ and all of its contents unless I'm missing something.

**Comment by claremacrae** [comment]
My guess is that that is machine-generated in the publishing process...

Got any more examples?

**Comment by AveryVeilfaire** [comment]
I think I have eventually found everything else. But it feels like that page is pretty key to organized usage. So lucky its online too.

**Comment by s-blu** [comment]
Hello,

Clares Guess is right: The tagindex is added exclusively to the online version, because the Overviews meant to be used in the Example Vault under 30 Dataview Resources/31 Query Overviews do not work in the Online version.

The tagindex is only included in the online version, because filtering/searching for tags is a built-in utility of Obsidian. You can open up the Tags-sidepanel, click on any tag you'd like to filter for and the search view will give you all pages tagged, with more possibilities for you to filter. 
![grafik](https://github.com/user-attachments/assets/e8744924-5de4-483b-887c-4a394e9a38c5)

Beside the tagindex, the privacy notice is also exclusive to the online version. All other pages are converted from the example vaults sources and thus, are part of the example vault.
